name: CI

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - name: Preparar artefato
        if: github.event_name == 'push'
        run: tar -czf build-artifacts.tgz .
      - name: Upload artefato
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build-artifacts.tgz
